resolver: nightly-2015-06-12
packages:
#- azure-service-api
- distributed-process
- distributed-process-async
#- distributed-process-azure
- distributed-process-client-server
#- distributed-process-demos
- distributed-process-execution
- distributed-process-extras
- distributed-process-simplelocalnet
- distributed-process-supervisor
- distributed-process-task
- distributed-process-tests
- distributed-static
- network-transport
- network-transport-composed
- network-transport-inmemory
- network-transport-tcp
- network-transport-tests
- rank1dynamic

extra-deps:
- asn1-data-0.7.1
- certificate-1.3.9
- libssh2-0.2.0.3
- rematch-0.2.0.0
- hxt-xpath-9.1.2.2
- tls-extra-0.6.6
