resolver: lts-4.2
packages:
- .
- distributed-process
- distributed-process/distributed-process-tests
- distributed-process-async
- distributed-process-client-server
- distributed-process-demos
- distributed-process-execution
- distributed-process-extras
- distributed-process-p2p
- distributed-process-registry
- distributed-process-simplelocalnet
- distributed-process-supervisor
- distributed-process-task
- distributed-static
- network-transport
- network-transport-composed
- network-transport-inmemory
- network-transport-tcp
- network-transport-tests
- network-transport-benchmarks
- rank1dynamic
# TODO Out-of-date packages
# - azure-service-api
# - distributed-process-azure

flags:
  distributed-process-tests:
    tcp: true
  distributed-process-demos:
    # Azure packages don't compile anymore.
    use-azure: False

extra-deps:
- rematch-0.2.0.0
