resolver: nightly-2015-06-05
packages:
- network-transport
- network-transport-composed
- network-transport-inmemory
- network-transport-tcp
- network-transport-tests
- rank1dynamic
- distributed-static
- distributed-process
- distributed-process-platform
- distributed-process-extras
- distributed-process-async
- distributed-process-client-server
- distributed-process-supervisor
- distributed-process-task
- distributed-process-execution
- distributed-process-tests
- distributed-process-azure
- distributed-process-demos
- distributed-process-simplelocalnet

